//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASAMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASAMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///echo Updating ARK: Survival Ascended...
        ///cd /d &quot;{0}&quot;
        ///steamcmd +login anonymous +force_install_dir &quot;{1}&quot; +app_update 2430930 validate +quit
        ///echo Starting ARK: Survival Ascended Server...
        ///cd /d &quot;{1}&quot;
        ///start ShooterGame\Binaries\Win64\ArkAscendedServer.exe {2} -WinLiveMaxPlayers={3} {4} {5} &quot;{6}?listen&quot;.
        /// </summary>
        internal static string BatchCmd {
            get {
                return ResourceManager.GetString("BatchCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ebb32c51_bda5_419c_8ac5_663b02598084 {
            get {
                object obj = ResourceManager.GetObject("ebb32c51-bda5-419c-8ac5-663b02598084", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;RecordDisplay&quot;&gt;
        ///                            &lt;label&gt;
        ///                                &lt;span class=&quot;FieldName&quot;&gt;&lt;label class=&quot;control-label&quot; for=&quot;ServerPassword&quot;&gt;Server Password:&lt;/label&gt;&lt;/span&gt;
        ///                                &lt;span class=&quot;FormInputField&quot;&gt;
        ///                                    &lt;input type=&quot;password&quot; id=&quot;ServerPassword&quot; name=&quot;ServerPassword&quot; value=&quot;{ServerPassword}&quot; /&gt;
        ///                                &lt;/span&gt;
        ///                            &lt;/label&gt;
        ///                        &lt;/div&gt;
        ///
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PasswordsHtml {
            get {
                return ResourceManager.GetString("PasswordsHtml", resourceCulture);
            }
        }
    }
}
