using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ASAMonitor
{
    public class ToggleButton
    {
        public static string CssString()
        {
            return CssString("No", "Yes", new System.Web.UI.WebControls.Unit("100px"), String.Empty);
        }

        public static string CssString(string offText, string onText, System.Web.UI.WebControls.Unit width)
        {
            return CssString(offText, onText, width, String.Empty);
        }

        public static string CssString(string offText, string onText, System.Web.UI.WebControls.Unit width, string scope)
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span::after,");
            sb.AppendLine(".toggleButton input[type=\"radio\"] + span::after");
            sb.AppendLine("{");
            sb.AppendLine("    content: \"" + offText + "\";");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"]:checked + span::after,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"]:checked + span::after");
            sb.AppendLine("{");
            sb.AppendLine("    content: \"" + onText + "\";");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton");
            sb.AppendLine("{");
            sb.AppendLine("    -moz-user-select: none;");
            sb.AppendLine("    -webkit-user-select: none;");
            sb.AppendLine("    user-select: none;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton");
            sb.AppendLine("{");
            //sb.AppendLine("    margin: 4px 0;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton label,");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span,");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span::after,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span::after");
            sb.AppendLine("{");
            sb.AppendLine("    display: inline-block;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton label");
            //sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span,");
            //sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span");
            sb.AppendLine("{");
            sb.AppendLine("    vertical-align: middle;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span,");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span::after,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span::after");
            sb.AppendLine("{");
            sb.AppendLine("    -moz-border-radius: 4px;");
            sb.AppendLine("    -webkit-border-radius: 4px;");
            sb.AppendLine("    border-radius: 4px;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span::after,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span::after,");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"]:checked + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"]:checked + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"]:checked + span::after,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"]:checked + span::after");
            sb.AppendLine("{");
            sb.AppendLine("    top: 0;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span::after,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span::after,");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"]:checked + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"]:checked + span::before");
            sb.AppendLine("{");
            sb.AppendLine("    right: 0;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"]:checked + span::after,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"]:checked + span::after");
            sb.AppendLine("{");
            sb.AppendLine("    left: 0;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"],");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"],");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span::after,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span::after");
            sb.AppendLine("{");
            sb.AppendLine("    position: absolute;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton label");
            sb.AppendLine("{");
            sb.AppendLine("    margin: 2px 0 2px 4px;");
            sb.AppendLine("    cursor: pointer;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"],");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"]");
            sb.AppendLine("{");
            sb.AppendLine("    filter: alpha(opacity=0);");
            sb.AppendLine("    -moz-opacity: 0;");
            sb.AppendLine("    -webkit-opacity: 0;");
            sb.AppendLine("    opacity: 0;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span");
            sb.AppendLine("{");
            sb.AppendLine("    width: " + width.ToString() + ";");
            sb.AppendLine("    height: 30px;");
            sb.AppendLine("    font: bold 14px/30px Arial, Sans-serif;");
            sb.AppendLine("    color: #8c8c8c;");
            sb.AppendLine("    text-transform: uppercase;");
            sb.AppendLine("    border: solid 1px #bcbbbb;");
            sb.AppendLine("    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=\"#c8c8c8\", endColorstr=\"#f3f3f3\");");
            sb.AppendLine("    background: -moz-linear-gradient(top, #c8c8c8, #f3f3f3);");
            sb.AppendLine("    background: -webkit-linear-gradient(top, #c8c8c8, #f3f3f3);");
            sb.AppendLine("    background: -o-linear-gradient(top, #c8c8c8, #f3f3f3);");
            sb.AppendLine("    background: -ms-linear-gradient(top, #c8c8c8, #f3f3f3);");
            sb.AppendLine("    background: linear-gradient(top, #c8c8c8, #f3f3f3);");
            sb.AppendLine("    position: relative;");
            sb.AppendLine("    text-indent: -9999px;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span::before");
            sb.AppendLine("{");
            sb.AppendLine("    content: \"\";");
            sb.AppendLine("    width: 40%;");
            sb.AppendLine("    height: 29px;");
            sb.AppendLine("    border-top: solid 1px #fff;");
            sb.AppendLine("    border-right: solid 1px #bebebe;");
            sb.AppendLine("    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=\"#cfcfcf\", endColorstr=\"#f9f9f9\");");
            sb.AppendLine("    background: -moz-linear-gradient(top, #cfcfcf, #f9f9f9);");
            sb.AppendLine("    background: -webkit-linear-gradient(top, #cfcfcf, #f9f9f9);");
            sb.AppendLine("    background: -o-linear-gradient(top, #cfcfcf, #f9f9f9);");
            sb.AppendLine("    background: -ms-linear-gradient(top, #cfcfcf, #f9f9f9);");
            sb.AppendLine("    background: linear-gradient(top, #cfcfcf, #f9f9f9);");
            sb.AppendLine("    -moz-box-shadow: 1px 0 1px #bebebe;");
            sb.AppendLine("    -webkit-box-shadow: 1px 0 1px #bebebe;");
            sb.AppendLine("    box-shadow: 1px 0 1px #bebebe;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"] + span::after,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"] + span::after");
            sb.AppendLine("{");
            sb.AppendLine("    text-indent: 0;");
            sb.AppendLine("    width: 62%;");
            sb.AppendLine("    height: 32px;");
            sb.AppendLine("    text-align: center;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"]:checked + span,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"]:checked + span");
            sb.AppendLine("{");
            sb.AppendLine("    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=\"#1b45bd\", endColorstr=\"#5d96ea\");");
            sb.AppendLine("    background: -moz-linear-gradient(top, #1b45bd, #5d96ea);");
            sb.AppendLine("    background: -webkit-linear-gradient(top, #1b45bd, #5d96ea);");
            sb.AppendLine("    background: -o-linear-gradient(top, #1b45bd, #5d96ea);");
            sb.AppendLine("    background: -ms-linear-gradient(top, #1b45bd, #5d96ea);");
            sb.AppendLine("    background: linear-gradient(top, #1b45bd, #5d96ea);");
            sb.AppendLine("    color: #fff;");
            sb.AppendLine("    text-shadow: -1px -1px #0d2046;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"]:checked + span::before,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"]:checked + span::before");
            sb.AppendLine("{");
            sb.AppendLine("    left: auto;");
            sb.AppendLine("    -moz-box-shadow: -2px 0 1px #3a5e91;");
            sb.AppendLine("    -webkit-box-shadow: -2px 0 1px #3a5e91;");
            sb.AppendLine("    box-shadow: -2px 0 1px #3a5e91;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton input[type=\"checkbox\"]:checked + span::after,");
            sb.AppendLine(scope + " .toggleButton input[type=\"radio\"]:checked + span::after");
            sb.AppendLine("{");
            sb.AppendLine("    border-top: solid 1px #0f2a4f;");
            sb.AppendLine("    border-bottom: solid 1px #0f2a4f;");
            sb.AppendLine("    border-left: solid 1px #2c5496;");
            sb.AppendLine("    height: 30px;");
            sb.AppendLine("    top: -1px;");
            sb.AppendLine("    left: -1px;");
            sb.AppendLine("    -moz-border-radius: 4px 0 0 4px;");
            sb.AppendLine("    -webkit-border-radius: 4px 0 0 4px;");
            sb.AppendLine("    border-radius: 4px 0 0 4px;");
            sb.AppendLine("}");
            sb.AppendLine(scope + " .toggleButton_browser-support li.ie6,");
            sb.AppendLine(scope + " .toggleButton_browser-support li.ie7,");
            sb.AppendLine(scope + " .toggleButton_browser-support li.ie8");
            sb.AppendLine("{");
            sb.AppendLine("    display: none;");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
